[workspace]
members = [
    "intl-messageformat-parser-rs",
    "intl-messageformat-parser-rs-napi",
    "intl-messageformat-parser-wasm",
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[profile.bench]
debug = true
